version: '3.7'
services:
    db:
        image: postgres:13
        restart: unless-stopped
        container_name: balbol_db
        env_file:
          - .env
        ports:
          - "5432:5432"
        volumes:
          - database-data:/var/lib/postgresql/data/
      
volumes:
  database-data:
          
      