version: '3.7'
services:
    web:
        build: .
        # Mapping of container port to host
        ports:
          - "${PORT}:5000"
        environment:
          ENV: 'DEVELOPMENT'
          FLASK_ENV: 'development'
          FLASK_APP: 'app'
          PYTHONUNBUFFERED: 1
      