version: '3.7'
services:
    web:
        build: .
        # Mapping of container port to host
        ports:
          - "${PORT}:5000"
        environment:
          ENV: 'PRODUCTION'
        env_file:
          - .env
        depends_on:
          - "db"
        ofelia.enabled: "true"
          ofelia.job-exec.get_today_games.schedule: "@0 30 8 * * *"
          ofelia.job-exec.get_today_games.command: "sh scripts/get_today_games.sh https://balbol.herokuapp.com"


    scheduler:
      image: mcuadros/ofelia:latest
      depends_on:
        - web
      command: daemon --docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
          
      